{
	"version": 1693073993,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/logo-sheet0.png",
		"images/background-default-000.jpg",
		"images/background2-default-000.jpg",
		"images/background3-default-000.jpg",
		"images/background4-default-000.jpg",
		"images/explosion1-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/playerlaser-sheet0.png",
		"images/gunflare-sheet0.png",
		"images/enemyspawner-sheet0.png",
		"images/enemybullet-sheet0.png",
		"images/enemybullet-sheet1.png",
		"images/bladeenemy-sheet0.png",
		"images/bladeenemy-sheet1.png",
		"images/explosion2-sheet0.png",
		"images/explosion3-sheet0.png",
		"images/explosion3-sheet1.png",
		"images/explosion3-sheet2.png",
		"images/healthbar.png",
		"images/healthbg.png",
		"images/spikeyenemy-sheet0.png",
		"images/spikeyenemy-sheet1.png",
		"images/playerrocket-sheet0.png",
		"images/rocketpowerup-sheet0.png",
		"images/rocketsdisplay.png",
		"images/playerthrust-sheet0.png",
		"images/bugenemy-sheet0.png",
		"images/bugenemy-sheet1.png",
		"images/enemylaser-sheet0.png",
		"images/fighterenemy-sheet0.png",
		"images/rocketbutton-sheet0.png",
		"mediayes/lazer fire 1.m4a",
		"mediayes/lazer fire 1.ogg",
		"mediayes/explosion 1.m4a",
		"mediayes/explosion 1.ogg",
		"mediayes/retrolaser1.m4a",
		"mediayes/retrolaser1.ogg",
		"mediayes/lazer ricochet.m4a",
		"mediayes/lazer ricochet.ogg",
		"mediayes/explosion 4.m4a",
		"mediayes/explosion 4.ogg",
		"mediayes/squaremotif1.m4a",
		"mediayes/squaremotif1.ogg",
		"mediayes/upgrade1.m4a",
		"mediayes/upgrade1.ogg",
		"mediayes/tronblast1.m4a",
		"mediayes/tronblast1.ogg",
		"mediayes/jetloop1.m4a",
		"mediayes/jetloop1.ogg",
		"mediayes/explosion 3.m4a",
		"mediayes/explosion 3.ogg",
		"mediayes/explosion 2.m4a",
		"mediayes/explosion 2.ogg",
		"mediayes/retrolaser2.m4a",
		"mediayes/retrolaser2.ogg",
		"mediayes/epicarpg.m4a",
		"mediayes/epicarpg.ogg",
		"mediayes/mattoglseby - 3.m4a",
		"mediayes/mattoglseby - 3.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}